# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: |
            ~/.m2/repository
            Paper/work/Minecraft
        key: ${{ runner.os }}-obw-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-obw
    - name: Clone Paper
      uses: actions/checkout@v2
      with:
        repository: PaperMC/Paper
        path: Paper
    - name: Patch and Build Paper
      run: |
        pwd
        ls
        cd Paper
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Github Actions"
        ./paper jar
    - name: Build OBW
      uses: actions/checkout@v2
      with:
        path: OBW
    - name: Build OBW
      run: |
          cd ../OBW
          mvn --batch-mode --update-snapshots verify
    - name: Restart server
      run: |
          curl "https://panel.knoban.com/api/client/servers/${{ secrets.PTERODACTYL_CONTAINER }}/power" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ secrets.PTERODACTYL_APITOKEN }}' \
          -X POST \
          -d '{"signal": "restart"}'
    - name: Upload OBW
      run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo $VERSION
          mv ./target/obw-$VERSION.jar ./target/OneBlockWide.jar
          curl "https://panel.knoban.com/api/client/servers/${{ secrets.PTERODACTYL_CONTAINER }}/files/delete" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ secrets.PTERODACTYL_APITOKEN }}' \
          -X POST \
          -d '{"root": "/plugins", "files": ["OneBlockWide.jar"]}'
          curl "https://panel.knoban.com/api/client/servers/${{ secrets.PTERODACTYL_CONTAINER }}/files/write?file=%2Fplugins%2FOneBlockWide.jar" \
          -H 'Accept: application/json' \
          -H 'Authorization: Bearer ${{ secrets.PTERODACTYL_APITOKEN }}' \
          -X POST \
          --data-binary '@./target/OneBlockWide.jar'
